//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="bizType", Namespace="http://example/")]
    public enum bizType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Leads = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shop = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Order = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://example/", ConfigurationName="ServiceReference1.HelloWorld")]
    public interface HelloWorld {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/sayHelloWorldFromRequest", ReplyAction="http://example/HelloWorld/sayHelloWorldFromResponse")]
        WpfApp1.ServiceReference1.sayHelloWorldFromResponse sayHelloWorldFrom(WpfApp1.ServiceReference1.sayHelloWorldFromRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/sayHelloWorldFromRequest", ReplyAction="http://example/HelloWorld/sayHelloWorldFromResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.sayHelloWorldFromResponse> sayHelloWorldFromAsync(WpfApp1.ServiceReference1.sayHelloWorldFromRequest request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/mobileSearchUpdateRequest", ReplyAction="http://example/HelloWorld/mobileSearchUpdateResponse")]
        WpfApp1.ServiceReference1.mobileSearchUpdateResponse mobileSearchUpdate(WpfApp1.ServiceReference1.mobileSearchUpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://example/HelloWorld/mobileSearchUpdateRequest", ReplyAction="http://example/HelloWorld/mobileSearchUpdateResponse")]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.mobileSearchUpdateResponse> mobileSearchUpdateAsync(WpfApp1.ServiceReference1.mobileSearchUpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloWorldFromRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHelloWorldFrom", Namespace="http://example/", Order=0)]
        public WpfApp1.ServiceReference1.sayHelloWorldFromRequestBody Body;
        
        public sayHelloWorldFromRequest() {
        }
        
        public sayHelloWorldFromRequest(WpfApp1.ServiceReference1.sayHelloWorldFromRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sayHelloWorldFromRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public sayHelloWorldFromRequestBody() {
        }
        
        public sayHelloWorldFromRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sayHelloWorldFromResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sayHelloWorldFromResponse", Namespace="http://example/", Order=0)]
        public WpfApp1.ServiceReference1.sayHelloWorldFromResponseBody Body;
        
        public sayHelloWorldFromResponse() {
        }
        
        public sayHelloWorldFromResponse(WpfApp1.ServiceReference1.sayHelloWorldFromResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class sayHelloWorldFromResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public sayHelloWorldFromResponseBody() {
        }
        
        public sayHelloWorldFromResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mobileSearchUpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mobileSearchUpdate", Namespace="http://example/", Order=0)]
        public WpfApp1.ServiceReference1.mobileSearchUpdateRequestBody Body;
        
        public mobileSearchUpdateRequest() {
        }
        
        public mobileSearchUpdateRequest(WpfApp1.ServiceReference1.mobileSearchUpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class mobileSearchUpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public WpfApp1.ServiceReference1.bizType arg1;
        
        public mobileSearchUpdateRequestBody() {
        }
        
        public mobileSearchUpdateRequestBody(string arg0, WpfApp1.ServiceReference1.bizType arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mobileSearchUpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mobileSearchUpdateResponse", Namespace="http://example/", Order=0)]
        public WpfApp1.ServiceReference1.mobileSearchUpdateResponseBody Body;
        
        public mobileSearchUpdateResponse() {
        }
        
        public mobileSearchUpdateResponse(WpfApp1.ServiceReference1.mobileSearchUpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class mobileSearchUpdateResponseBody {
        
        public mobileSearchUpdateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldChannel : WpfApp1.ServiceReference1.HelloWorld, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldClient : System.ServiceModel.ClientBase<WpfApp1.ServiceReference1.HelloWorld>, WpfApp1.ServiceReference1.HelloWorld {
        
        public HelloWorldClient() {
        }
        
        public HelloWorldClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.ServiceReference1.sayHelloWorldFromResponse WpfApp1.ServiceReference1.HelloWorld.sayHelloWorldFrom(WpfApp1.ServiceReference1.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFrom(request);
        }
        
        public string sayHelloWorldFrom(string arg0) {
            WpfApp1.ServiceReference1.sayHelloWorldFromRequest inValue = new WpfApp1.ServiceReference1.sayHelloWorldFromRequest();
            inValue.Body = new WpfApp1.ServiceReference1.sayHelloWorldFromRequestBody();
            inValue.Body.arg0 = arg0;
            WpfApp1.ServiceReference1.sayHelloWorldFromResponse retVal = ((WpfApp1.ServiceReference1.HelloWorld)(this)).sayHelloWorldFrom(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.sayHelloWorldFromResponse> WpfApp1.ServiceReference1.HelloWorld.sayHelloWorldFromAsync(WpfApp1.ServiceReference1.sayHelloWorldFromRequest request) {
            return base.Channel.sayHelloWorldFromAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.sayHelloWorldFromResponse> sayHelloWorldFromAsync(string arg0) {
            WpfApp1.ServiceReference1.sayHelloWorldFromRequest inValue = new WpfApp1.ServiceReference1.sayHelloWorldFromRequest();
            inValue.Body = new WpfApp1.ServiceReference1.sayHelloWorldFromRequestBody();
            inValue.Body.arg0 = arg0;
            return ((WpfApp1.ServiceReference1.HelloWorld)(this)).sayHelloWorldFromAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfApp1.ServiceReference1.mobileSearchUpdateResponse WpfApp1.ServiceReference1.HelloWorld.mobileSearchUpdate(WpfApp1.ServiceReference1.mobileSearchUpdateRequest request) {
            return base.Channel.mobileSearchUpdate(request);
        }
        
        public void mobileSearchUpdate(string arg0, WpfApp1.ServiceReference1.bizType arg1) {
            WpfApp1.ServiceReference1.mobileSearchUpdateRequest inValue = new WpfApp1.ServiceReference1.mobileSearchUpdateRequest();
            inValue.Body = new WpfApp1.ServiceReference1.mobileSearchUpdateRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            WpfApp1.ServiceReference1.mobileSearchUpdateResponse retVal = ((WpfApp1.ServiceReference1.HelloWorld)(this)).mobileSearchUpdate(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfApp1.ServiceReference1.mobileSearchUpdateResponse> WpfApp1.ServiceReference1.HelloWorld.mobileSearchUpdateAsync(WpfApp1.ServiceReference1.mobileSearchUpdateRequest request) {
            return base.Channel.mobileSearchUpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfApp1.ServiceReference1.mobileSearchUpdateResponse> mobileSearchUpdateAsync(string arg0, WpfApp1.ServiceReference1.bizType arg1) {
            WpfApp1.ServiceReference1.mobileSearchUpdateRequest inValue = new WpfApp1.ServiceReference1.mobileSearchUpdateRequest();
            inValue.Body = new WpfApp1.ServiceReference1.mobileSearchUpdateRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((WpfApp1.ServiceReference1.HelloWorld)(this)).mobileSearchUpdateAsync(inValue);
        }
    }
}
